language: node_js
node_js:
  - 10

branches:
  only: master

before_install:
- openssl aes-256-cbc -K $encrypted_6d931d8515f6_key -iv $encrypted_6d931d8515f6_iv
  -in gcp-client-secret.json.enc -out gcp-client-secret.json -d

install:
- npm install
script:
- npm run build

deploy:
  provider: gae
  keyfile: gcp-client-secret.json
  project: stripe-terminal-demo
  skip_cleanup: true

